---
envVarGroups:
  - name: shared-auth
    envVars:
      - key: AUTH_BEARER_TOKEN
        sync: false

services:
  - type: web
    name: ai-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/v1/health
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ai-db
          property: connectionString
      - fromGroup:
          name: shared-auth

  - type: web
    name: ai-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: BACKEND_URL
        fromService:
          name: ai-backend
          type: web
          property: url
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          name: ai-backend
          type: web
          property: url
      - fromGroup:
          name: shared-auth

databases:
  - name: ai-db
    plan: free
